fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
        exclude: ^templates/
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [-b, main]
      - id: check-added-large-files
        args: [--maxkb=1000]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: ^templates/
        args:
          [
            -d,
            "{extends: default, rules: {line-length: {max: 200}, document-start: disable}}",
          ]

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.1.0
    hooks:
      - id: tofu_fmt
        exclude: ^templates/
      - id: tofu_validate
        exclude: ^templates/
        args:
          - --hook-config=--retry-once-with-cleanup=true
